force-app/main/default/objects/Case_Config__c/Case_Config__c.object-meta.xml
<CustomObject>
    <label>Case Config</label>
    <nameField>
        <displayFormat>Case Config # {0000}</displayFormat>
        <label>Case Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Config__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Configs</relationshipLabel>
    <relationshipName>Case_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Config__c/Config__c.object-meta.xml
<CustomObject>
    <label>Config</label>
    <nameField>
        <displayFormat>Config #{0000}</displayFormat>
        <label>Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestFactory.cls
@isTest
public class TestFactory {
  public static void makeData() {
    Case cs = new Case();
    cs.Subject = 'Test Subject';
    insert cs;

    List<Case_Config__c> csConfigList = new List<Case_Config__c>();
    for (Integer i = 1; i < 3; i++) {
      Case_Config__c csConfig = new Case_Config__c();
      csConfig.Label__c = 'Label ' + i;
      csConfig.Type__c = 'Type ' + i;
      csConfig.Amount__c = 100 * i;
      csConfig.Case__c = cs.Id;
      csConfigList.add(csConfig);
    }

    insert csConfigList;

    List<Config__c> cfgList = new List<Config__c>();

    for (Integer i = 1; i < 6; i++) {
      Config__c config = new Config__c();
      config.Label__c = 'Label ' + i;
      config.Type__c = 'Type ' + i;
      config.Amount__c = 100 * i;
      cfgList.add(config);
    }
    insert cfgList;
  }
}