force-app/main/default/objects/Config__c/Config__c.object-meta.xml
<CustomObject>
    <label>Config</label>
    <nameField>
        <displayFormat>Config #{0000}</displayFormat>
        <label>Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AvailableConfigsControllerTest.cls
@isTest
class AvailableConfigsControllerTest {
  @TestSetup
  static void makeData() {
    TestFactory.makeData();
  }

  @IsTest
  static void getAllConfigsTest() {
    Test.startTest();
    List<Config__c> configList = AvailableConfigsController.getAllConfigs();
    Test.stopTest();
    System.assert(!configList.isEmpty());
  }

  @IsTest
  static void addConfigsToCaseTest() {
    Id caseId = [SELECT Id FROM Case LIMIT 1]?.Id;
    List<Config__c> configs = [
      SELECT Label__c, Type__c, Amount__c
      FROM Config__c
    ];
    Test.startTest();
    Object results = AvailableConfigsController.addConfigsToCase(
      caseId,
      configs
    );
    Test.stopTest();
    System.assert(results != null);
  }

  @IsTest
  static void addConfigsToCaseNegativeTest1() {
    Test.startTest();
    try {
      Object obj = AvailableConfigsController.addConfigsToCase(null, null);
    } catch (Exception e) {
      System.assertEquals('Script-thrown exception', e.getMessage());
    }
    Test.stopTest();
  }
  @IsTest
  static void addConfigsToCaseNegativeTest2() {
    Id caseId = [SELECT Id FROM Case LIMIT 1]?.Id;
    List<Config__c> configs = [SELECT Label__c FROM Config__c];
    Test.startTest();
    try {
      Object obj = AvailableConfigsController.addConfigsToCase(caseId, configs);
    } catch (Exception e) {
      System.assertEquals('Script-thrown exception', e.getMessage());
    }
    Test.stopTest();
  }
}